Task 2. SSSP
achains/high-performance-graph-analysis-course pull request #2
Opened 2022-04-14 16:06 UTC by achains

# Задача 2. Реализация поиска кратчайших путей

* **Мягкий дедлайн**: ---
* **Жёсткий дедлайн**: 14.04.2022, 23:59
* Полный балл: 15

## Задача

Везде считаем, что вершины графа занумерованы подряд с нуля.
Обратите внимание на то, что про граф заранее не известно, есть ли в нём циклы отрицательного веса.

- [x] Используя pygraphblas реализовать функцию поиска кратчайших путей в ориентированном графе из заданной вершины.
  - [x] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно) и номер стартовой вершины.
  - [x] Функция возвращает массив, где для каждой вершины указано расстояние до неё от указанной стартовой вершины. Если вершина не достижима, то значение соответствующей ячейки равно -1.
- [x] Используя pygraphblas реализовать функцию поиска кратчайших путей в ориентированном графе из нескольких заданных вершин.
  - [x] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно) и массив номеров стартовых вершин.
  - [x] Функция возвращает массив пар: вершина, и массив, где для каждой вершины указано расстояние до неё из указанной. Если вершина не достижима, то значение соответствующей ячейки равно -1.
- [x] Добавить необходимые тесты.

2022-05-28 16:23 UTC, gsvgit requested changes

2022-05-28 16:23 UTC, gsvgit commented on project/sssp.py
> +    for _ in range(matrix.nrows):
Можно ли как-то оптимизировать этот цикл? Предположим, что граф огромен (10^8 вершин) а пути в нём короткие (считанные десятки рёбер). Думается, в таком случае цикл будет избыточным.

2022-05-28 16:23 UTC, gsvgit commented on tests/test_bfs.py
> +from project.bfs import bfs, multi_bfs
А что будет, если в графе нет рёбер? А если всего одна вершина?  И т.д. Как-то скудно с тестами.

2022-05-28 16:23 UTC, gsvgit commented on tests/test_sssp.py
> +from project.sssp import sssp, mssp
Тоже с тестами скудновато.

2022-06-05 18:25 UTC, achains commented on project/sssp.py
> +    for _ in range(matrix.nrows):
Done

2022-06-05 18:25 UTC, achains commented on tests/test_bfs.py
> +from project.bfs import bfs, multi_bfs
добавил тестов в первый PR

2022-06-05 18:26 UTC, achains commented on tests/test_sssp.py
> +from project.sssp import sssp, mssp
Добавил

2022-06-06 06:16 UTC, gsvgit commented on project/bfs.py
> +def _bfs(matrix: gb.Matrix, start_node_list):
А сделайте, пожалуйста, так, чтобы в реквесте по задаче было только то, что имеет отношение к этой задаче.

2022-06-06 11:25 UTC, closed without merging