Task 3. Triangle Count
achains/high-performance-graph-analysis-course pull request #3
Opened 2022-04-21 20:34 UTC by achains

# Задача 3. Реализация подсчёта треугольников

* **Мягкий дедлайн**: ---
* **Жёсткий дедлайн**: 21.04.2022, 23:59
* Полный балл: 15

## Задача

Везде считаем, что вершины графа занумерованы подряд с нуля.

- [x] Используя pygraphblas реализовать функцию, вычисляющую для каждой вершины количество треугольников, в которых она участвует.
  - [x] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно. Обратите внимание, что надо позаботиться о том, чтобы граф был неориентированным. ) и номер стартовой вершины.
  - [x] Функция возвращает массив, где для каждой вершины указано, в скольки треугольниках она участвует.
- [x] Добавить необходимые тесты.

2022-05-28 16:25 UTC, gsvgit requested changes

2022-05-28 16:25 UTC, gsvgit commented on project/bfs.py
> +import pygraphblas as gb
А зачем Вы в один реквест лепите всё? Даже то, что не имеет отношения к сдаваемой задаче?

2022-05-28 16:25 UTC, gsvgit commented on project/sssp.py
> +import pygraphblas as gb
Выделите только то, что относится к данной задаче.

2022-06-05 18:38 UTC, achains commented
Мне эти PR'ы закрыть и в новые ветки от main перенести?

2022-06-06 06:18 UTC, gsvgit requested changes

2022-06-06 06:18 UTC, gsvgit commented on project/bfs.py
> +import pygraphblas as gb
Повторю свой вопрос. И превращу в просьбу. Сделайте, пожалуйста, так, чтобы в реквесте было только то, что имеет непосредственное отношение к задаче.

2022-06-06 11:24 UTC, closed without merging